server:
  port: 8082

spring:
  application:
    name: employee-manage
  datasource:
    url: jdbc:mysql://47.93.52.76:3306/employee?useUnicode=true&characterEncoding=utf-8
    username: zyk
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#
#  thymeleaf:
#    #关闭thymeleaf的缓存
#    cache: false
#    #controller返回指定页面时的路径前后缀
#    prefix: classpath:/templates/
#    suffix=: .html
#    encoding: UTF-8
#    check-template-location: true
#    mode: HTML5
#    servlet:
#      content-type: text/html


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.lm.employee.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker

      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
    # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

